config/routes.rb
Rails.application.routes.draw do
 
  root 'static_pages#home'
  
  get    '/help', 		to: 'static_pages#help'
  get    '/signup', 	to: 'users#new'
  post   '/signup', 	to: 'users#create'
  get    '/login', 		to: 'sessions#new'
  post   '/login', 		to: 'sessions#create'
  delete '/logout', 	to: 'sessions#destroy'
  
  resources :users
   
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	before_save { name.downcase! }
	validates :name, presence: true, 
									 length: { maximum: 15 }, 
									 uniqueness: { case_sensitive: false }

	has_secure_password
	validates :password, presence: true, length: { minimum: 3}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  
  end

  def create
  	user = User.find_by(name: params[:session][:name].downcase)
  	if user && user.authenticate(params[:session][:password])
  		log_in user
  		redirect_to root_url
  	else  		
  		render 'new'
  	end
  end
  
  def destroy
    log_out
    redirect_to root_url  
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save  		
  		 redirect_to root_url
  	else
  		render 'new'
  	end
  end
 

  private

  def user_params
  	params.require(:user).permit(:name, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	#distinct method session of RoR that writes users id to temporary cookie
	#in form of hash :user_id
	def log_in(incoming_user_entity_got_from_form)
		session[:user_id] = incoming_user_entity_got_from_form.id 
	end

	#if in session was written user_id this hooks found by id user object 
	#into the global variable and returns it
	def current_user
		if session[:user_id]
			@current_user ||= User.find_by(id: session[:user_id])
		end
	end

	#boolean method that checks if the user object persists
	def logged_in?
		!current_user.nil?
	end

	#clears user's id, written to the session method and also clears @current_user
	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IO | <%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	 <%= yield %> 
	</body>

</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	The form contains <%= pluralize(@user.errors.count, "error") %>.
	<ul>
		<% @user.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>

app/views/static_pages/help.html.erb
<% provide(:title, "Home") %>

	<li><%= link_to "Home", root_path %></li>
 	<% if logged_in? %> 			
 			<li><%= link_to "Logout", logout_path, method: :delete%></li>
 		<% else %>
 			
 	<% end %>
 

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
	
	<li><%= link_to "Home", root_path %></li> 	
 	
 	<% if logged_in? %>
 			<li><%= link_to "Help", help_path %></li>
 			<li><%= link_to "Logout", logout_path, method: :delete%></li>
 		<% else %>
 			<li><%= link_to "Log in", login_path %></li>
 			<li><%= link_to "Sign up", signup_path %></li>
 	<% end %>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>

<li><%= link_to "Home", root_path %></li>
<li><%= link_to "Help", help_path %></li>

<h1>Sign up</h1>

	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<%= form_for(@user, url: signup_path) do |f| %>
			<%= render 'shared/error_messages' %>
			
				<li><%= f.label :name %></li>
				<li><%= f.text_field :name, class: 'form_control' %></li>

				<li><%= f.label :password %></li>
				<li><%= f.password_field :password, class: 'form_control' %></li>

				<li><%= f.label :password_confirmation, "Confirmation" %></li>
				<li><%= f.password_field :password_confirmation, class: 'form_control' %></li>

				<li><%= f.submit "Create account", class: "btn btn-primary" %></li>

			<% end %>

		</div>
	</div>